name: Update NPM dependencies

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      config:
        description: 'Config'
        required: false
        default: ''
        
name: Invoke workflow with inputs
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: Update NPM dependencies
    token: ${{ secrets.GH_WORKFLOWS_TOKEN }}
    inputs: '{ "bump": "true" }'
