name: Bump dependencies
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      config:
        description: 'Config'
        required: false
        default: ''

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Read config
        run: |
          CONFIG='{}'
          if [[ ! -z '${{ github.event.inputs.config }}' ]]; then
            CONFIG='${{ github.event.inputs.config }}'
          elif [[ -f "./.github/workflows-config.json" ]]; then
            CONFIG=$( jq -c .updateDeps './.github/workflows-config.json' )
          fi
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
          echo "Workflow config: $CONFIG"
      - name: Merge configs
        run: |
          # Add bump property set on 'true'
          CONFIG=$(echo '${{ env.CONFIG }}' | jq --arg bump true)
          echo '${{env.CONFIG}}'
      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update NPM dependencies
          token: ${{ secrets.GH_WORKFLOWS_TOKEN }}
          inputs: ${{ env.CONFIG }}
          # '{ "config": "{\"targetBranch\":\"master\"}" }'
